// 자동 생성된 코드입니다. 편집하지 마십시오.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "air ddd":return img`
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.......................................
........................................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.......................................
........................................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.......................................
........................................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.......................................
........................................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.......................................
........................................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.......................................
........................................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.......................................
............................fffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfffffffffff.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddfffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddfffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfffffffffffffffffffdddddddddffff1111fffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddffff1111fffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddfff11111fffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddfff11111fffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddfff1fffffffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddfffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddffff1111fffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbfffbbbfdddddddddffff1111fffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbfffbbbfdddddddddffff1111fffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbfffbbbfdddddddddfff11111fffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbfffbbbbbbfdddddddddfffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbfffbbbbbbfdddddddddfffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbfffbbbbbbfdddddddddfff11111fffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddfff11111fffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddfff1f1fffffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbffffffbbbfdddddddddfff1f1f1fffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbffffffbbbfdddddddddfff11111fffffdddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbffffffbbbfdddddddddfffffffffffffdddddddddddddddfffffffffdddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbffffffbbbfdddddddddfffffffffffffdddddddddddddff222222222ffdddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbffffffbbbfddddddddddddddddddddddddddddddddddf2222222222222fddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbffffffbbbfdddddddddddddddddddddddddddddddddf222222222222222fdddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfddddddddddddddddddddddddddddddddf22222222222222222fddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddddddddddddddddddddddddf2222222222222222222fdddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddddddddddddddddddddddddf22222222fff22222222fdddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbfffbbbfddddddddddddddddddddddddddddddf222222222fff222222222fddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbfffbbbfddddddddddddddddddddddddddddddf22222222fffff22222222fddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbfffbbbfddddddddddddddddddddddddddddddf22222222ff2ff22222222fddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbfffbbbbbbfddddddddddddddddddddddddddddddf22222222ff2ff22222222fddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbfffbbbbbbfddddddddddddddddddddddddddddddf2222222ff222ff2222222fddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbfffbbbbbbfddddddddddddddddddddddddddddddf2222222ff222ff2222222fddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbfffbbbfddddddddddddddddddddddddddddddf222222fffffffff222222fddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbfffbbbfddddddddddddddddddddddddddddddf222222ff22222ff222222fddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbfffbbbfddddddddddddddddddddddddddddddf222222ff22222ff222222fddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbffffffbbbfdddddddddddddddddddddddddddddddf22222ff22222ff22222fdddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbffffffbbbfdddddddddddddddddddddddddddddddf2222222222222222222fdddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbffffffbbbfddddddddddddddddddddddddddddddddf22222222222222222fddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddddddddddddddddddddddddddf222222222222222fdddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfddddddddddddddddddddddddddddddddddf2222222222222fddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddddddddddddddddddddddddddddff222222222ffdddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddddddddddddddddddddddddddddddfffffffffdddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfbbbbbbbbbbbbbbbbbfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddfffffffffffffffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddf.............................
............................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.............................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
................................................................................................................................................................
`;
            case "image2":
            case "space":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffff1ffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffff1fffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffff1f1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff111fff1fff111fffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffff1fffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "image3":
            case "destroyer":return img`
..................................................
..................................................
......................ffffff......................
....................ffbbbbbbff....................
...................fbbbbbbbbbbf...................
..................fbbbbbbbbbbbbf..................
..................fbbbbbbbbbbbbf..................
.................fbbbbbbbbbbbbbcf.................
.................fbbbbbbbbbbbbbcf.................
.................fbbbbbbbbbbbbccf.................
.................fbbbbbbbbbbbbccf.................
.................fbbbbbbbbbbbbccf.................
.................fbbbbbbbbbbbcccf.................
..................fbbbbbbbbbbccf..................
..................fbbbbbbbbccccf..................
...................fbbbbbcccccf...................
....................ffccccccff....................
......................ffffff......................
.......................fccf.......................
.......................fbcf.......................
.......................fbcf.......................
.......................fbcf.......................
.......................fbcf.......................
.......................fbcf.......................
.......................fbcf.......................
.......................fbcf.......................
.......................fbcf.......................
......................ffbcff......................
.....................fbfbcfcf.....................
.....................ffbffcff.....................
.....................fbffffcf.....................
.....................fbfbbfcf.....................
.....................fbfbbfcf.....................
.....................fbfbbfcf.....................
.....................fbfbbfcf.....................
.....................fbfbbfcf.....................
.....................fbfbbfcf.....................
.....................fbfbbfcf.....................
.....................fbfbbfcf.....................
.....................fbfbbfcf.....................
.....................fbfbbfcf.....................
.................fffffbfbbfcfffff.................
..........fffffffbbbbfbfbbfcfbbbbffffff...........
....ffffffbbbbbbbbbbbfbfbbfcfbbbbbbbbbbfffffff....
ffffbbbbbbbbbbbbbbbbbfbfbbfcfbbbbbbbbbbbbbbbbbffff
fbbffffbbbbbbbbbbbbbbfbfbbfcfcccbbbbbbbbbbbffffbbf
fbbbbbbffffbbbbbbbbbbbffbbffccccccccbbbffffbbbbbbf
fbbbbbbbbbbfffffbbbbbbbffffcccccccfffffbbbbbbbbcbf
fbbbbbbbbbbbbbbbfffffbbbbbbbcfffffbbbbbbbbbcbbbcbf
fbbbbbbbbbbbbbbbbbbbbffffffffbbbbbbbbbbcbbbcbbbcbf
fbbbbbbbbbbbbbbbbbbbbfbbbbbbfbbbbbcbbbbcbbbcbbbcbf
fbbbbbbbbbbbbbbbbbbbbfbbbbbbfbbbbbcbbbbcbbbcbbbccf
fbbbbbbbbbbbbbbbbbbbbfbbbbbbfbbbbbcbbbbcbbbcbbbccf
fbbbbbbbbbbbbbbbbbbbbfbbbbbbfbbbbbcbbbbcbbbcbbbccf
fbbbbbbbbbbbbbbbbbbbbfbbbbbbfbbbbbcbbbbcbbbcbbbccf
fbbbbbbbbbbbbbbbbbbbbfbbbbbbfbbbbbcbbbbcbbbcbbbccf
fbbbbbbbbbbbbbbbbbbbbfbbbbbbfbbbbbcbbbbcbbbcbbbccf
fbbbbbbbbbbbbbbbbbbbbfbbbbbbfbbbbbcbbbbcbbbccccccf
fffbbbbbbbbbbbbbbbbbbfbbbbbbfbbbbbcbbbbccccccccfff
...ffffbbbbbbbbbbbbbbfbbbbbbfbbbbbcccccccccffff...
.......ffffbbbbbbbbbbfbbbbbcfccccccccccffff.......
...........fffffbbbbbfccccccfcccccfffff...........
................ffffffccccccffffff................
.....................ffffffff.....................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
`;
            case "image4":
            case "missile":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . 2 3 3 2 . . . . . . 
. . . . . 2 3 1 1 3 2 . . . . . 
. . . . 2 3 1 1 1 1 3 2 . . . . 
. . . . 2 3 1 1 1 1 3 2 . . . . 
. . . . 2 3 1 1 1 1 3 2 . . . . 
. . . . 2 3 3 1 1 3 3 2 . . . . 
. . . . . 2 3 1 1 3 2 . . . . . 
. . . . . 2 3 1 1 3 2 . . . . . 
. . . . . 2 3 1 1 3 2 . . . . . 
. . . . . 2 3 1 1 3 2 . . . . . 
. . . . . . 2 1 1 2 . . . . . . 
. . . . . . . 1 1 . . . . . . . 
. . . . . . . 1 1 . . . . . . . 
. . . . . . . 1 1 . . . . . . . 
`;
            case "image5":
            case "gg":return img`
. . . . . 5 5 5 5 5 . . . . . 
. . . . 5 5 5 5 5 5 5 . . . . 
. . . . 5 5 f 5 f 5 5 . . . . 
. . . . 5 5 5 5 5 5 5 . . . . 
. . . . 5 5 f f f 5 5 . . . . 
. . . . 5 5 5 5 5 5 5 . . . . 
. . . . . 5 5 5 5 5 . . . . . 
. . 5 5 5 5 5 5 5 5 5 5 5 . . 
. . 5 5 5 5 5 5 5 5 5 5 5 . . 
. . 5 5 5 5 5 5 5 5 5 5 5 . . 
. . 5 5 5 5 5 5 5 5 5 5 5 . . 
. . 5 5 5 5 5 5 5 5 5 5 5 . . 
. . . . 5 5 5 5 5 5 5 . . . . 
. . . . 5 5 5 . 5 5 5 . . . . 
. . . . 5 5 5 . 5 5 5 . . . . 
. . . . 5 5 5 . 5 5 5 . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// 자동 생성된 코드입니다. 편집하지 마십시오.
